# Generated by Django 4.2.dev20230113113141 on 2023-01-21 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pieceofart',
            old_name='release_date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='pieceofart',
            old_name='directory',
            new_name='creator',
        ),
        migrations.RemoveField(
            model_name='pieceofart',
            name='cast',
        ),
    ]
