# Generated by Django 4.2.dev20230113113141 on 2023-01-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_release_date_pieceofart_creation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pieceofart',
            old_name='creation_date',
            new_name='creation_year',
        ),
    ]
