# Generated by Django 4.2.dev20230113113141 on 2023-01-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_creation_date_pieceofart_creation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceofart',
            name='image',
            field=models.URLField(default=None, null=True),
        ),
    ]
