# Generated by Django 4.2.dev20230113113141 on 2023-01-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pieceofart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieceofart',
            name='averageRating',
            field=models.FloatField(default=0),
        ),
    ]
